### health check
GET http://localhost:5000/health-check HTTP/1.1

### registration
POST http://localhost:5000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{   
    "username": "Test One",
    "email": "test1@fakemail.com",
    "password": "1234"
}

### login
POST http://localhost:5000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{   
    "email": "test1@fakemail.com",
    "password": "1234"
}

### refresh token
POST http://localhost:5000/api/v1/auth/refresh-token HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoicmVmcmVzaCIsInByb2ZpbGUiOnsiaWQiOiJiNzUzYTk4OS1iNmYyLTRiNDQtOGI1MC0wNzU3MTc0NmIwNjQiLCJlbWFpbCI6InRlc3QxQGZha2VtYWlsLmNvbSIsInVzZXJuYW1lIjoiVGVzdCBPbmUiLCJhdXRoUHJvdmlkZXIiOiJ2aW9sYSIsImF2YXRhclVybCI6IiIsInZlcmlmaWVkIjpmYWxzZSwicHJlbWl1bSI6ZmFsc2UsInJvbGUiOiJtZW1iZXIiLCJzZXR0aW5ncyI6e30sImNyZWF0ZWRBdCI6IjIwMjUtMDctMDlUMDI6Mzc6NTYuOTI5WiIsImxhc3RMb2dpbkF0IjoiIn0sImlhdCI6MTc1MjA4MjU4MCwiZXhwIjoxNzUyMTYxNzgwLCJhdWQiOiJiNzUzYTk4OS1iNmYyLTRiNDQtOGI1MC0wNzU3MTc0NmIwNjQiLCJpc3MiOiJ2aW9sYS5yYWdodWdhbm5hcmFtLmNvbSJ9.kqqRnzhE91XYobQ984LJ5-4vVTsrqYkUG_VxNBbv6XE

### logout
DELETE http://localhost:5000/api/v1/auth/logout HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoicmVmcmVzaCIsInByb2ZpbGUiOnsiaWQiOiJiNzUzYTk4OS1iNmYyLTRiNDQtOGI1MC0wNzU3MTc0NmIwNjQiLCJlbWFpbCI6InRlc3QxQGZha2VtYWlsLmNvbSIsInVzZXJuYW1lIjoiVGVzdCBPbmUiLCJhdXRoUHJvdmlkZXIiOiJ2aW9sYSIsImF2YXRhclVybCI6IiIsInZlcmlmaWVkIjpmYWxzZSwicHJlbWl1bSI6ZmFsc2UsInJvbGUiOiJtZW1iZXIiLCJzZXR0aW5ncyI6e30sImNyZWF0ZWRBdCI6IjIwMjUtMDctMDlUMDI6Mzc6NTYuOTI5WiIsImxhc3RMb2dpbkF0IjoiIn0sImlhdCI6MTc1MjA4MjYwOCwiZXhwIjoxNzUyMTYxODA4LCJhdWQiOiJiNzUzYTk4OS1iNmYyLTRiNDQtOGI1MC0wNzU3MTc0NmIwNjQiLCJpc3MiOiJ2aW9sYS5yYWdodWdhbm5hcmFtLmNvbSJ9.lYSx3_c9I1qq1ViGWCJpdH6GXq24FplovQMTKFiTuYo



### stream
GET http://localhost:5000/api/v1/audio/stream/2f5e1471-d523-4149-8544-9cbb20c38c05 HTTP/1.1
Content-Type: application/json

### identify audio
GET http://localhost:5000/api/v1/audio/identify HTTP/1.1
Content-Type: application/json

### tracks
GET http://localhost:5000/api/v1/audio/tracks HTTP/1.1
Content-Type: application/json

### track by id
GET http://localhost:5000/api/v1/audio/tracks/2f5e1471-d523-4149-8544-9cbb20c38c05 HTTP/1.1
Content-Type: application/json

### albums
GET http://localhost:5000/api/v1/audio/albums HTTP/1.1
Content-Type: application/json

### album by id
GET http://localhost:5000/api/v1/audio/albums/181b1cb0-d31a-4992-95f0-51247ed3399e HTTP/1.1
Content-Type: application/json

### artists
GET http://localhost:5000/api/v1/audio/artists HTTP/1.1
Content-Type: application/json

### artist by id
GET http://localhost:5000/api/v1/audio/artists/181b1cb0-7da1-40f8-a908-fa8c21e6d59c HTTP/1.1
Content-Type: application/json