const filenameContaminants: string[] = [
	// Indian / South Asian piracy sources
	"isongs",
	"naasongs",
	"starmusiq",
	"tamilanda",
	"raag",
	"raagfm",
	"djjohal",
	"mrjatt",
	"mr-jatt",
	"djpunjab",
	"songs.pk",
	"songspk",
	"0pk",
	"desimaza",
	"desitorrents",
	"desibees",
	"teluguwap",
	"hindikala",
	"bolly4u",

	// Pakistani / Bangladeshi
	"funmaza",
	"funmazaa",
	"mp3mad",
	"mp3song",
	"mymp3song",
	"songxpress",
	"mobimasti",

	// Global / General piracy sites
	"pagalworld",
	"djmaza",
	"webmusic",
	"songslover",
	"bee-music",
	"vipmusic",
	"redmusic",
	"mp3goo",
	"mp3juices",
	"bestwap",
	"123musiq",
	"myfreemp3",
	"freeallmusic",
	"mp3raid",
	"wapking",
	"dhamakaking",
	"mp3clan",
	"songsmp3",
	"kingmusic",
	"topgaana",
	"youtubemp3",

	// Common embedded artifacts in filenames
	"original",
	"official",
	"fullsong",
	"new",
	"remix",
	"lyrics",
	"video",
	"320kbps",
	"128kbps",
	"hd",
	"ultra",
	"hindi",
	"telugu",
	"tamil",
];

const mimeToExtension: Record<string, string> = {
	"audio/mpeg": "mp3",
	"audio/wav": "wav",
	"audio/flac": "flac",
	"audio/aac": "aac",
	"audio/ogg": "ogg",
	"audio/x-aiff": "aiff",
	"audio/x-m4a": "m4a",

	"image/jpeg": "jpg",
	"image/png": "png",
	"image/webp": "webp",
};

export default {
	filenameContaminants,
	mimeToExtension,
};
